#리소스팩 자동배포
http:
  # 외부에서 접속 가능한 공인 IP 또는 도메인을 적어야 합니다.
  # 로컬 테스트 시: 127.0.0.1
  # 친구와 할 때: 내 컴퓨터의 IPv4 주소 (예: 192.168.0.15)
  host: "127.0.0.1"
  port: 8123

#리소스팩 다운로드 강제화 및 안내 메세지
resourcepack:
  required: true
  prompt: "§e서버의 리소스팩을 다운로드해야 정상적인 플레이가 가능합니다.\n§b[예]§f를 눌러주세요."
  kick-message: "§c리소스팩을 거절하여 접속이 종료되었습니다."